### ISSUE TITLE
Alignment Issue - WIE / CS / Volunteer

### ISSUE THREAD

**Issue by SanjulaD** [IEEE-Student-Branch-NSBM/IEEENSBM#50]
![image](https://user-images.githubusercontent.com/49508237/182178858-8b3397d2-9403-46d4-b145-77b851b5b1cc.png)

![image](https://user-images.githubusercontent.com/49508237/182178892-f3408074-f275-4d5a-b73d-a208b52cd0a8.png)

![image](https://user-images.githubusercontent.com/49508237/182179296-bddcf96a-f214-498d-ae8d-7a6b546ccf70.png)

**Comment by prineth** [comment]
I'll fix this
